title: Sergio Belmontes # your name (or website title) here
logo: "photo1.jpg" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
 Hello, I'm Sergio Belmontes, I am a young GIS Professional currently working as a GIS Technician.
 As a GIS specialist I usually wear different hats when asked. Sometimes it may involve spatial analysis with ArcGIS Pro, or computing spatial statistics in RStudio.
 The next day I may be processing LANDSAT 8 data and acquiring remotely sensed LiDAR drone data.
 The following day I may be editing designs in AuotCAD to help bear some of the workload found in the engineering department.
 Finally, I may be running some Python to help automate daily workflows.
 I may be a GIS specialist, but my perspective is always geo-referenced.
  <br><br>
  <a href="https://www.linkedin.com/in/sergio-belmontes-9ab126175/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
